
package com.wisdom.area.webservice.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.417+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "InvalidMessageContentExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class InvalidMessageContentExpressionFault extends Exception {

    private InvalidMessageContentExpressionFaultType faultInfo;

    public InvalidMessageContentExpressionFault() {
        super();
    }

    public InvalidMessageContentExpressionFault(java.lang.String message) {
        super(message);
    }

    public InvalidMessageContentExpressionFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidMessageContentExpressionFault(java.lang.String message, InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault) {
        super(message);
        this.faultInfo = invalidMessageContentExpressionFault;
    }

    public InvalidMessageContentExpressionFault(java.lang.String message, InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidMessageContentExpressionFault;
    }

    public InvalidMessageContentExpressionFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
