
package com.wisdom.area.webservice.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.419+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "InvalidProducerPropertiesExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class InvalidProducerPropertiesExpressionFault extends Exception {

    private InvalidProducerPropertiesExpressionFaultType faultInfo;

    public InvalidProducerPropertiesExpressionFault() {
        super();
    }

    public InvalidProducerPropertiesExpressionFault(java.lang.String message) {
        super(message);
    }

    public InvalidProducerPropertiesExpressionFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidProducerPropertiesExpressionFault(java.lang.String message, InvalidProducerPropertiesExpressionFaultType invalidProducerPropertiesExpressionFault) {
        super(message);
        this.faultInfo = invalidProducerPropertiesExpressionFault;
    }

    public InvalidProducerPropertiesExpressionFault(java.lang.String message, InvalidProducerPropertiesExpressionFaultType invalidProducerPropertiesExpressionFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidProducerPropertiesExpressionFault;
    }

    public InvalidProducerPropertiesExpressionFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
