
package com.wisdom.area.webservice.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.397+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "NoCurrentMessageOnTopicFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class NoCurrentMessageOnTopicFault extends Exception {

    private NoCurrentMessageOnTopicFaultType faultInfo;

    public NoCurrentMessageOnTopicFault() {
        super();
    }

    public NoCurrentMessageOnTopicFault(java.lang.String message) {
        super(message);
    }

    public NoCurrentMessageOnTopicFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public NoCurrentMessageOnTopicFault(java.lang.String message, NoCurrentMessageOnTopicFaultType noCurrentMessageOnTopicFault) {
        super(message);
        this.faultInfo = noCurrentMessageOnTopicFault;
    }

    public NoCurrentMessageOnTopicFault(java.lang.String message, NoCurrentMessageOnTopicFaultType noCurrentMessageOnTopicFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = noCurrentMessageOnTopicFault;
    }

    public NoCurrentMessageOnTopicFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
