
package com.wisdom.area.webservice.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.381+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "ResourceUnknownFault", targetNamespace = "http://docs.oasis-open.org/wsrf/r-2")
public class ResourceUnknownFault extends Exception {

    private ResourceUnknownFaultType faultInfo;

    public ResourceUnknownFault() {
        super();
    }

    public ResourceUnknownFault(java.lang.String message) {
        super(message);
    }

    public ResourceUnknownFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceUnknownFault(java.lang.String message, ResourceUnknownFaultType resourceUnknownFault) {
        super(message);
        this.faultInfo = resourceUnknownFault;
    }

    public ResourceUnknownFault(java.lang.String message, ResourceUnknownFaultType resourceUnknownFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = resourceUnknownFault;
    }

    public ResourceUnknownFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
