
package com.wisdom.area.webservice.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.411+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "TopicExpressionDialectUnknownFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class TopicExpressionDialectUnknownFault extends Exception {

    private TopicExpressionDialectUnknownFaultType faultInfo;

    public TopicExpressionDialectUnknownFault() {
        super();
    }

    public TopicExpressionDialectUnknownFault(java.lang.String message) {
        super(message);
    }

    public TopicExpressionDialectUnknownFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public TopicExpressionDialectUnknownFault(java.lang.String message, TopicExpressionDialectUnknownFaultType topicExpressionDialectUnknownFault) {
        super(message);
        this.faultInfo = topicExpressionDialectUnknownFault;
    }

    public TopicExpressionDialectUnknownFault(java.lang.String message, TopicExpressionDialectUnknownFaultType topicExpressionDialectUnknownFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = topicExpressionDialectUnknownFault;
    }

    public TopicExpressionDialectUnknownFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
